name: Test install-prerequisites.sh on Linux

on:
  workflow_dispatch:

jobs:
  test-linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: ubuntu-latest
            name: AmazonLinux
            container: amazonlinux:2023

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Run install-prerequisites.sh
        run: bash install-prerequisites.sh
